---
title: "barsDetective"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

# Plot

```{r global}
# load librarys
if (!require("pacman")){                                  
    install.packages("pacman")}                       
pacman::p_load(
  pacman,
  data.table,
  tidyverse,
  ggeasy,
  Rcpp,
  glue,
  plyr,
  lubridate,
  shiny,
  DT,
  flexdashboard,
  stringi,
  plotly,
  colorspace,
  ggthemes,
  ggeasy,
  colourpicker
  )

```


```{r}
#n <- 24000
#
## gen the random data
#data <- 
#    data.table(
#      y1 = rnorm(n) + seq(0, 0.5, length.out = n),
#      y2 = rnorm(n, mean = -0.25, sd = 2),
#      y3 = rnorm(n, mean = 0.25, sd = 1.5),
#      y4 = rnorm(n, mean = 0.5, sd = 1.5),
#      group1 = sample(c("yin", "yang"), n, replace = T),
#      group2 = sample(c("tora", "avoda", "gmilot_hasadim"), n, replace = T),
#      group3 = sample(c("fire", "air", "water", "earth"), n, replace = T),
#      group4 = sample(c("i", "ii", "iii", "iv", "v"), n, replace = T)
#    )



 data <-
   as.data.table(
   ggplot2::diamonds
   )


#data <-
#  as.data.table(
#  mtcars
#  )
#
#data$cyl <- as.factor(data$cyl)
#data$vs <- as.factor(data$vs)
#data$am <- as.factor(data$am)


#data <-
#  as.data.table(
#  iris
#  )

data <- 
data %>%
  mutate_if(is.integer,as.numeric) 

```


```{r}

# num cols:
num_col_names <- 
  names(data)[
    unlist(lapply(data, is.numeric))
    ]

# char cols:
chr_col_names <- 
  names(data)[
    unlist(lapply(data, is.character)) |
    unlist(lapply(data, is.factor))
    ]
```


Column {.sidebar data-width=150}
-----------------------------------------------------------------------

<br>
```{r}
# set the user selection sidebar ----

selectInput(
  'x',
  label = 'x',
  chr_col_names,
  selected = chr_col_names[1]
  )

selectInput(
  'y',
  label = 'y',
  num_col_names,
  selected= num_col_names[1]
  )

radioButtons(
  "add_text",
  "add_text",
  choices = c("yes", "no"),
  selected = "no"
)

```


Column
-----------------------------------------------------------------------

### 

```{r}
# create data pivot ----
data_for_plot <- 
  reactive({
    
    ColSelect <- input$x

    data[, 
       ntile := ntile(get(input$y), 10),
       by = ColSelect]

    join_all(
        list(
          data[ntile == 10, .(mean_top = mean(get(input$y))), ColSelect],
          data[ntile == 1, .(mean_bottom = mean(get(input$y))), ColSelect],
          data[, .(mean = mean(get(input$y))), ColSelect],
          data[, .(median = median(get(input$y))), ColSelect]
        ),
        by = input$x
      )
    
})
```


```{r}
# create plot ----

renderPlot({
  # create
range <- max(data_for_plot()$mean_top) - min(data_for_plot()$mean_bottom)
tick_width <- 0.004  

g <- 
data_for_plot() %>% 
  ggplot() +
  geom_segment(
    aes_string(
      x = "mean_bottom",
      xend = "mean_top",
      y = input$x,
      yend = input$x
    ),
    size = input$m_segment_size,
    color = input$m_segment_color
  ) +
  geom_segment(
    aes_string(
      x = "mean",
      xend = "median",
      y = input$x,
      yend = input$x
    ),
    size = input$m_segment_size,
    color = input$i_segment_color
  ) +
  geom_segment(
    aes(
      x = mean,
      xend = mean + input$line_size * range,
      y = get(input$x),
      yend = get(input$x)
    ),
    size = input$m_segment_size,
    color = input$mean_color
  ) +
  geom_segment(
    aes(
      x = median,
      xend = median - input$line_size * range,
      y = get(input$x),
      yend = get(input$x)
    ),
    size = input$m_segment_size,
    color = input$median_color
  ) +
  scale_x_continuous(
    breaks = scales::pretty_breaks(n = 8)
  ) +
  theme_classic() +
  easy_remove_y_axis(what = c("ticks")) +
  easy_remove_x_axis(what = c("line", "ticks")) +
  labs(
    title = glue("asironim of {input$y} by {input$x}"),
    subtitle = "",
    x = "",
    y = ""
  ) +
   ### theming ----
    theme(
      # panel and grid
      plot.background = 
        element_rect(
          fill = input$plot_background_color
          ),
      panel.background = 
        element_rect(
          fill = input$panel_background_color,
          size = 0.5, 
          linetype = "solid"
          ),
      
      panel.grid.major.x = element_line(size = input$grid_size, colour = input$grid_color),
      
      # labs
      plot.title = 
        element_text(
          color="black", size=input$title_size, face="bold"
          ),
      plot.subtitle = 
        element_text(
          size = input$subtitle_size ,color="black", face="bold", hjust = 0.05
          ),
     axis.text = 
       element_text( 
         color="black", 
         face = "bold",
         size = input$axis_size
         ),
     axis.ticks = element_blank() 
     
    )


if(input$add_text == "no"){
  g
} else{
  g + 
    geom_text(
    aes(
      x = mean_bottom,
      y = get(input$x),
      label = scales::comma(mean_bottom, accuracy = 0.01)
      ),
     hjust = 1 + input$geom_text_hjust,
     fontface = "bold",
     size = input$geom_text_size
    ) + 
    geom_text(
    aes(
      x = mean_top,
      y = get(input$x),
      label = scales::comma(mean_top, accuracy = 0.01)
      ),
     hjust = -1* input$geom_text_hjust,
     fontface = "bold",
     size = input$geom_text_size
    ) 
}

})
```

# raw data

```{r}
renderDataTable(
  datatable(data_for_plot())
)
```

# data for plot

```{r}
renderDataTable(
  datatable(data)
)
```



# Design

## panel and data

### **main segment**


```{r}

# set the user selecton sidebar
sliderInput("m_segment_size", label = "m_segment_size:",
            min = 0.2, max = 50, value = 25, step = 0.1)

colourInput(
  "m_segment_color", "m_segment_color", "#45688E",
  allowTransparent = TRUE, closeOnClick = TRUE)

```


### **inner segment**

```{r}

sliderInput("line_size", label = "line_size:",
            min = 0.001, max = 0.01, value = 0.004, step = 0.0005)

colourInput(
  "i_segment_color", "i_segment_color", "#07006F",
  allowTransparent = TRUE, closeOnClick = TRUE)


```

### **mean line**

```{r}

colourInput(
  "mean_color", "mean_color", "#1BFF00",
  allowTransparent = TRUE, closeOnClick = TRUE)


```

### **median line**

```{r}

colourInput(
  "median_color", "median_color", "#FF9E00",
  allowTransparent = TRUE, closeOnClick = TRUE)


```


## grid and panel

### **plot.background**

```{r}
colourInput(
  "plot_background_color", NULL, "gray98",
  allowTransparent = TRUE, closeOnClick = TRUE)
```

### **panel.background**

```{r}
colourInput(
  "panel_background_color", NULL, "gray98",
  allowTransparent = TRUE, closeOnClick = TRUE)
```

### **panel.grid**

```{r}
sliderInput("grid_size", label = "grid_size:",
            min = 0.1, max = 5, value = 0.9, step = 0.1)

colourInput(
  "grid_color", NULL, "gray70",
  allowTransparent = TRUE, closeOnClick = TRUE)
```


## labels

### **axis**

```{r}
sliderInput("axis_size", label = "axis_size:",
            min = 4, max = 20, value = 16, step = 0.25)
```

### **title**

```{r}
sliderInput("title_size", label = "title_size:",
            min = 4, max = 40, value = 28, step = 0.25)
```

### **subtitle**

```{r}
sliderInput("subtitle_size", label = "subtitle_size:",
            min = 4, max = 40, value = 16, step = 0.25)
```


### **geom text**

```{r}
sliderInput("geom_text_size", label = "geom_text_size:",
            min = 1, max = 40, value = 4.5, step = 0.25)

sliderInput("geom_text_hjust", label = "geom_text_hjust:",
            min = -2, max = 2, value = 0.205, step = 0.01)

```

