---
title: "barsDetective"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

# Plot

```{r global}
# load librarys
if (!require("pacman")){                                  
    install.packages("pacman")}                       
pacman::p_load(
  pacman,
  data.table,
  tidyverse,
  ggeasy,
  Rcpp,
  glue,
  lubridate,
  shiny,
  DT,
  flexdashboard,
  stringi,
  plotly,
  colorspace,
  ggthemes,
  ggeasy,
  colourpicker
  )

# f for R^2 -> R function on vector, 
# by the name of the function
f <- function(f_name, vector){
      if(f_name == "mean"){
        return(mean(vector))
      } else if(f_name == "sum"){
        return(sum(vector))
      } else if(f_name == "min"){
        return(min(vector))
      } else if(f_name == "max"){
        return(max(vector))
      } else if(f_name == "sd"){
        return(sd(vector))
      } else if(f_name == "count"){
        return(length(vector))
      } else if(f_name == "uniqueN"){
        return(uniqueN(vector))
      } else if(f_name == "median"){
        return(median(vector))
      }else if(f_name == "sum_NA"){
        return(sum(is.na(vector)))
      }
}


f_to <- function(n, fname, name1, name2, name3, name4){
  if(n == 1){
    list(f(fname,name1))
  } else if(n == 2){
    list(f(fname,name1),f(fname,name2))
  } else if(n == 3){
    list(f(fname,name1),f(fname,name2),f(fname,name3))
  } else if(n == 4){
    list(f(fname,name1),f(fname,name2),f(fname,name3),f(fname,name4))
  }
}
```


```{r}
#n <- 24000
#
## gen the random data
#data <- 
#    data.table(
#      y1 = rnorm(n) + seq(0, 0.5, length.out = n),
#      y2 = rnorm(n, mean = -0.25, sd = 2),
#      y3 = rnorm(n, mean = 0.25, sd = 1.5),
#      y4 = rnorm(n, mean = 0.5, sd = 1.5),
#      group1 = sample(c("yin", "yang"), n, replace = T),
#      group2 = sample(c("tora", "avoda", "gmilot_hasadim"), n, replace = T),
#      group3 = sample(c("fire", "air", "water", "earth"), n, replace = T),
#      group4 = sample(c("i", "ii", "iii", "iv", "v"), n, replace = T)
#    )


data <-
  as.data.table(
  ggplot2::diamonds
  )

#data <-
#  as.data.table(
#  mtcars
#  )
#data$cyl <- as.factor(data$cyl)
#data$vs <- as.factor(data$vs)
#data$am <- as.factor(data$am)


#data <-
#  as.data.table(
#  iris
#  )


data <- 
data %>%
  mutate_if(is.integer,as.numeric) 
```


```{r}
# num cols:
num_col_names <- 
  names(data)[
    unlist(lapply(data, is.numeric))
    ]

# char cols:
chr_col_names <- 
  names(data)[
    unlist(lapply(data, is.character)) |
    unlist(lapply(data, is.factor))
    ]
```


Column {.sidebar data-width=150}
----

<br>
```{r}
# set the user selection sidebar ----

selectInput(
  'f',
  label = 'f',
  c("mean", "sum", "min", "max", "sd", "count", "uniqueN", "median", "sum_NA"),
  selected= 'mean'
  )

selectInput(
  'x',
  label = 'x',
  chr_col_names,
  selected = chr_col_names[1]
  )

selectInput(
  'y1',
  label = 'y1',
  num_col_names,
  selected = num_col_names[1]
  )

selectInput(
  'y2',
  label = 'y2',
  c(".", num_col_names),
  selected = "." 
  )

selectInput(
  'y3',
  label = 'y3',
  c(".", num_col_names),
  selected = "."
  )

selectInput(
  'y4',
  label = 'y4',
  c(".", num_col_names),
  selected = "."
  )

selectInput(
  'position',
  label = 'position',
  c("dodge2", "dodge", "fill", "stack"),
  selected= "dodge2"
  )

selectInput(
  'palette',
  label = 'palette',
  c("Set1", "Set2", "Set3", "Accent", "Dark2", "Paired", "Pastel1", "Pastel2"),
  selected = "Set1"
  )


radioButtons(
  "x_to_y",
  "x_to_y",
  choices = c("yes", "no"),
  selected = "no",
  inline = TRUE
)

radioButtons(
  "flip_axis",
  "flip_axis",
  choices = c("yes", "no"),
  selected = "no",
  inline = TRUE

)



#radioButtons(
#  "add_text",
#  "add_text",
#  choices = c("yes", "no"),
#  selected = "no"
#)
#

```


Column
------

### 

```{r}
# create data pivot ----
ord_name_x <- "ord_x"
ord_name_by <- "ord_by"

# create
data_for_plot <- 
  reactive({
    ColSelect <- input$x
    
    name_for_piv <- 
      c(input$y1, input$y2, input$y3, input$y4)[
        c(input$y1, input$y2, input$y3, input$y4) != "."
      ]
    
    num_of_series <- 
        4 - sum(
          c(".", ".", ".", ".") ==
          c(input$y1, input$y2, input$y3, input$y4)
        )    
    
    
    ## no fill_by
    data[,
         setNames(
         f_to(
           num_of_series,
           input$f,
           get(input$y1),
           get(input$y2), 
           get(input$y3),
           get(input$y4)
           ),
         name_for_piv),
        by = ColSelect] %>% 
      melt(input$x)
  })
```



```{r}
# create plot ----
renderPlot({
  # create
  if(input$x_to_y == "no"){
      g <- 
      data_for_plot() %>% 
        ggplot() +
          aes_string(x = input$x, y = "value", fill = "variable") + 
          geom_bar(stat = "identity",
                   position = input$position,
                   width = 0.6) 
  } else{
      g <- 
      data_for_plot() %>% 
        ggplot() +
          aes_string(fill = input$x, y = "value", x = "variable") + 
          geom_bar(stat = "identity",
                   position = input$position,
                   width = 0.6) 
  }
  
  if(input$flip_axis == "yes"){
    g <- 
      g +
      theme_classic() +
      coord_flip() +
      ## axis look management
      easy_remove_x_axis(what = c("line", "ticks")) +
      easy_remove_y_axis(what = c("ticks")) +
      theme(
      ## grid
      panel.grid.major.x = element_line( size=0.5, color="gray90") 
    ) 

  } else{
    g <- 
      g +
      theme_classic() +
      ## axis look management
      easy_remove_y_axis(what = c("line", "ticks")) +
      easy_remove_x_axis(what = c("ticks")) +
      theme(
      ## grid
      panel.grid.major.y = element_line( size=0.5, color="gray90") 
    ) 

  }
  
  
  # serve
  g <- 
  g +

    ## color palette
    scale_fill_brewer(palette=input$palette) + 

    ## start x from zero
    scale_y_continuous(
      expand = c(0, NA)
    ) +

    ## add text labels to the plot
    labs(
      title = glue::glue('{input$f} by {input$x}'),
      subtitle = glue::glue('show: {input$y1}, {input$y2}, {input$y3}, {input$y4}'),
      x = "",
      y = "",
      fill = ""
    ) +

    ## set customize theme
    theme(
      # legend
     legend.justification = "top"
    ) 
    ## no cliping to my plot!
    #coord_cartesian(clip = 'off')
  
  g
})
```

# plot data

```{r}
renderDataTable(
  datatable(data_for_plot())
)
```


# full data

```{r}
renderDataTable(
  datatable(data)
)
```


