---
title: "barsDetective"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

# Plot

```{r global}
# load librarys
if (!require("pacman")){                                  
    install.packages("pacman")}                       
pacman::p_load(
  pacman,
  data.table,
  tidyverse,
  ggeasy,
  Rcpp,
  glue,
  lubridate,
  shiny,
  flexdashboard,
  stringi,
  plotly,
  colorspace,
  ggthemes,
  ggeasy,
  colourpicker
  )

# f for R^2 -> R function on vector, 
# by the name of the function
f <- function(f_name, vector){
      if(f_name == "mean"){
        return(mean(vector))
      } else if(f_name == "sum"){
        return(sum(vector))
      } else if(f_name == "min"){
        return(min(vector))
      } else if(f_name == "max"){
        return(max(vector))
      } else if(f_name == "sd"){
        return(sd(vector))
      } else if(f_name == "count"){
        return(length(vector))
      } else if(f_name == "uniqueN"){
        return(uniqueN(vector))
      } else if(f_name == "median"){
        return(median(vector))
      }else if(f_name == "sum_NA"){
        return(sum(is.na(vector)))
      }
}
```


```{r}
#n <- 24000
#
## gen the random data
#data <- 
#    data.table(
#      y1 = rnorm(n) + seq(0, 0.5, length.out = n),
#      y2 = rnorm(n, mean = -0.25, sd = 2),
#      y3 = rnorm(n, mean = 0.25, sd = 1.5),
#      y4 = rnorm(n, mean = 0.5, sd = 1.5),
#      group1 = sample(c("yin", "yang"), n, replace = T),
#      group2 = sample(c("tora", "avoda", "gmilot_hasadim"), n, replace = T),
#      group3 = sample(c("fire", "air", "water", "earth"), n, replace = T),
#      group4 = sample(c("i", "ii", "iii", "iv", "v"), n, replace = T)
#    )


#data <-
#  as.data.table(
#  ggplot2::diamonds
#  )

data <-
  as.data.table(
  mtcars
  )
data$cyl <- as.factor(data$cyl)
data$vs <- as.factor(data$vs)
data$am <- as.factor(data$am)


#data <-
#  as.data.table(
#  iris
#  )
```


```{r}

# num cols:
num_col_names <- 
  names(data)[
    unlist(lapply(data, is.numeric))
    ]

# char cols:
chr_col_names <- 
  names(data)[
    unlist(lapply(data, is.character)) |
    unlist(lapply(data, is.factor))
    ]
```


Column {.sidebar data-width=150}
-----------------------------------------------------------------------

<br>
```{r}
# set the user selection sidebar ----

selectInput(
  'f',
  label = 'f',
  c("mean", "sum", "min", "max", "sd", "count", "uniqueN", "median", "sum_NA"),
  selected= 'mean'
  )

selectInput(
  'x',
  label = 'x',
  chr_col_names,
  selected = chr_col_names[1]
  )

selectInput(
  'y',
  label = 'y',
  num_col_names,
  selected= num_col_names[1]
  )

selectInput(
  'fill_by',
  label = 'fill_by',
  c(".", chr_col_names),
  selected= '.'
  )

selectInput(
  'position',
  label = 'position',
  c(".", "dodge", "fill", "stack"),
  selected= '.'
  )

radioButtons(
  "add_text",
  "add_text",
  choices = c("yes", "no"),
  selected = "no"
)

selectInput(
  'palette',
  label = 'palette',
  c("Set1", "Set2", "Set3", "Accent", "Dark2", "Paired", "Pastel1", "Pastel2"),
  selected = "Set1"
  )
```


Column
-----------------------------------------------------------------------

### 

```{r}
# create data pivot ----
ord_name_x <- "ord_x"
ord_name_by <- "ord_by"

# create
data_for_plot <- 
  reactive({
    ## no fill_by
    if(input$fill_by == "."){
    ColSelect <- input$x
    data[,
        .(
         V1 = f(input$f, get(input$y))
         ),
        by = ColSelect][, (ord_name_x) := fct_reorder(get(input$x), -V1)]
    
    ## yes fill_by
    } else {
          ColSelect <- c(input$x, input$fill_by)
          data[,
              .(
               V1 = f(input$f, get(input$y))
               ),
              by = ColSelect][, 
                  (ord_name_x) := fct_reorder(get(input$x), -V1)][,
                  (ord_name_by) := fct_reorder(get(input$fill_by), -V1)]
    }
    
  })
```


```{r}
# create plot ----

renderPlot({
  # create
  ## no fill_by
  if(input$fill_by == "."){
  g <- 
    data_for_plot() %>% 
    ggplot() +
      aes_string(x = "ord_x", y = "V1", fill = "ord_x") + 
      geom_bar(stat = "identity",
               width = 0.6)
  
  ## yes fill_by
  } else {
      if(input$position %in% c(".", "dodge")){
            g <- 
            data_for_plot() %>% 
            ggplot() +
              aes_string(x = "ord_x", y = "V1", fill = "ord_by") + 
              geom_bar(stat = "identity",
                       position = position_dodge2(preserve = "single"))
      } else if(input$position == "fill"){
            g <- 
            data_for_plot() %>% 
            ggplot() +
              aes_string(x = "ord_x", y = "V1", fill = "ord_by") + 
              geom_bar(stat = "identity",
                       position = "fill",
                       width = 0.6)
      } else{
            g <- 
            data_for_plot() %>% 
            ggplot() +
              aes_string(x = "ord_x", y = "V1", fill = "ord_by") + 
              geom_bar(stat = "identity",
                       width = 0.6)
      }
  }
  
  # add text label to bar
  ## no fill_by
  if(input$add_text == "yes"){
    if(input$position == "." & input$fill_by == "."){
          g <- 
            g +
            geom_text(
              aes(
                label = scales::comma(V1, accuracy = 0.01)
                ),
               vjust=-0.25,
               fontface = "bold"
              )
          
    ## yes fill_by
    } else if(input$position == "dodge" || (input$position == "." & input$fill_by != ".")){
          g <- 
             g +
             geom_text(
               aes(
                 label = scales::comma(V1, accuracy = 0.01)
                 ),
               position=position_dodge(width=0.9),
               vjust=-0.25
               )
    } else if(input$position == "fill"){
          g <- 
             g +
             geom_text(
               aes(
                 label = scales::comma(V1, accuracy = 0.01)
                 ),
               position=position_fill(0.5),
               fontface = "bold"
               )
    } else if(input$position == "stack"){
          g <- 
             g +
             geom_text(
               aes(
                 label = scales::comma(V1, accuracy = 0.01)
                 ),
               position=position_stack(0.5),
               fontface = "bold"
               )
    }
  }
  
  # serve
  g +
    ## main theme
    theme_classic() +
    
    ## color palette
    scale_fill_brewer(palette=input$palette) + 
    
    ## start x from zero
    scale_y_continuous(
      expand = c(0, NA)
    ) +
    
    ## axis look management
    easy_remove_y_axis(what = c("line", "ticks")) +
    easy_remove_x_axis(what = c("ticks")) +
    
    ## add text labels to the plot
    labs(
      title = glue::glue("{input$f} of {input$y} by {input$x}"),
      subtitle = glue::glue("break on: {input$fill_by}"),
      x = "",
      y = "",
      fill = ""
    ) +
    
    ## set customize theme
    theme(
      # legend
      legend.position = "top",
      
      ## grid
      panel.grid.major.y = element_line( size=0.5, color="gray90") 
      
    ) +
    ## no cliping to my plot!
    coord_cartesian(clip = 'off')
})
```



