---
title: "AnomalyDetective"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r}
# set environment ----

## load librarys
pacman::p_load(
  pacman,
  data.table,
  tidyverse,
  ggeasy,
  Rcpp,
  DT,
  glue,
  lubridate,
  shiny,
  flexdashboard,
  stringi,
  plotly,
  ggthemes,
  colourpicker,
  ggplot2,
  esquisse,
  ragg
  )
```


```{r}
# create proj functions ----

## gen res plot
plot_res <- function(data, x_name, y_name){
  data %>% 
  ggplot() +
  aes_string(x = x_name, y = y_name) +
  geom_line() +
  geom_hline(yintercept = 0, color = "green") +
  geom_hline(
    yintercept = 
      sd(data[, get(y_name)]), 
    color = "blue"
  ) +
  geom_hline(
    yintercept = 
      -sd(data[, get(y_name)]), 
    color = "blue"
  ) +
  geom_hline(
    yintercept = 
      2*sd(data[, get(y_name)]), 
    color = "yellow"
  ) +
  geom_hline(
    yintercept = 
      -2*sd(data[, get(y_name)]), 
    color = "yellow"
  ) +
  geom_hline(
    yintercept = 
      3*sd(data[, get(y_name)]), 
    color = "red"
  ) +
  geom_hline(
    yintercept = 
      -3*sd(data[, get(y_name)]), 
    color = "red"
  ) +
  theme_classic()
}

## gen raw data plot
plot_raw <- function(data, x_name, y_name){
  data %>% 
  ggplot() +
  aes_string(x = x_name, y = y_name) +
  geom_line() +
  theme_classic()
}
```

```{r}
# gen raw data ----
n <- 1000
m <- 100

dt <- 
  as.data.table(
  matrix(
    0, n, m
  )
)

dt$index <- 1:n

for(i in 1:m){
  dt[, i] <- 
    dt[, ..i] + 
      (sample(seq(0.5, 10, 0.05), 1) * 1:n) +
      rnorm(n, mean = 0, sd =(sample(seq(10, 20, 0.25), 1)))
}
```

```{r}
# gen data for plot
data_for_plot <- data.table(x = dt$index)
for(name in names(dt)){
  data_for_plot[, name] <- 
    lm(
      get(name) ~ index,
      data = dt
        )$residuals
}
```


# Main

Column {.sidebar data-width=150}
-----------------------------------------------------------------------

<br>
```{r}
# set the user selection sidebar

selectInput(
  'names',
  label = 'names',
  names(dt),
  selected = names(dt)[1]
  )

```


Row
-----------------------------------------------------------------------

### 


```{r}
## create plot ----
renderPlot({


data_for_arg_plots <- 
  data.table(
    names = names(map_dbl(data_for_plot[, -c("index", "x")],sd)),
    vals = map_dbl(data_for_plot[, -c("index", "x")],sd)
  )

data_for_arg_plots %>% 
  ggplot() +
  aes(x = names, y = vals) +
  geom_bar(stat = "identity")

})
```


# Grid

Column {.sidebar data-width=150}
-----------------------------------------------------------------------

<br>
```{r}
# set the user selection sidebar

selectInput(
  'V_1_grid',
  label = 'V_1_grid',
  names(dt),
  selected = names(dt)[1]
  )

selectInput(
  'V_2_grid',
  label = 'V_2_grid',
  names(dt),
  selected = names(dt)[2]
  )

selectInput(
  'V_3_grid',
  label = 'V_3_grid',
  names(dt),
  selected = names(dt)[3]
  )

selectInput(
  'V_4_grid',
  label = 'V_4_grid',
  names(dt),
  selected = names(dt)[4]
  )

selectInput(
  'V_5_grid',
  label = 'V_5_grid',
  names(dt),
  selected = names(dt)[5]
  )

selectInput(
  'V_6_grid',
  label = 'V_6_grid',
  names(dt),
  selected = names(dt)[6]
  )


selectInput(
  'V_7_grid',
  label = 'V_7_grid',
  names(dt),
  selected = names(dt)[7]
  )

selectInput(
  'V_8_grid',
  label = 'V_8_grid',
  names(dt),
  selected = names(dt)[8]
  )

selectInput(
  'V_9_grid',
  label = 'V_9_grid',
  names(dt),
  selected = names(dt)[9]
  )


radioButtons(
  "show_for_grid",
  "show_for_grid",
  c("only res", "only raw"),
  "only res"
)

```


Row
-----------------------------------------------------------------------

### 


```{r}
## create plot ----
renderPlot({

# create diff plots 
g_diff_for_grid_1 <- 
  plot_res(data_for_plot, "x", input$V_1_grid)

g_diff_for_grid_2 <- 
  plot_res(data_for_plot, "x", input$V_2_grid)

g_diff_for_grid_3 <- 
  plot_res(data_for_plot, "x", input$V_3_grid)

g_diff_for_grid_4 <- 
  plot_res(data_for_plot, "x", input$V_4_grid)

g_diff_for_grid_5 <- 
  plot_res(data_for_plot, "x", input$V_5_grid)

g_diff_for_grid_6 <- 
  plot_res(data_for_plot, "x", input$V_6_grid)

g_diff_for_grid_7 <- 
  plot_res(data_for_plot, "x", input$V_7_grid)

g_diff_for_grid_8 <- 
  plot_res(data_for_plot, "x", input$V_8_grid)

g_diff_for_grid_9 <- 
  plot_res(data_for_plot, "x", input$V_9_grid)

# create raw plots 
g_raw_for_grid_1 <- 
  plot_raw(dt, "index", input$V_1_grid)

g_raw_for_grid_2 <- 
  plot_raw(dt, "index", input$V_2_grid)

g_raw_for_grid_3 <- 
  plot_raw(dt, "index", input$V_3_grid)

g_raw_for_grid_4 <- 
  plot_raw(dt, "index", input$V_4_grid)

g_raw_for_grid_5 <- 
  plot_raw(dt, "index", input$V_5_grid)

g_raw_for_grid_6 <- 
  plot_raw(dt, "index", input$V_6_grid)

g_raw_for_grid_7 <- 
  plot_raw(dt, "index", input$V_7_grid)

g_raw_for_grid_8 <- 
  plot_raw(dt, "index", input$V_8_grid)

g_raw_for_grid_9 <- 
  plot_raw(dt, "index", input$V_9_grid)

# serve plots
if(input$show_for_grid == "only res"){
  (g_diff_for_grid_1 + g_diff_for_grid_2 + g_diff_for_grid_3) /
  (g_diff_for_grid_4 + g_diff_for_grid_5 + g_diff_for_grid_6) /
  (g_diff_for_grid_7 + g_diff_for_grid_8 + g_diff_for_grid_9)

} else{
  (g_raw_for_grid_1 + g_raw_for_grid_2 + g_raw_for_grid_3) /
  (g_raw_for_grid_4 + g_raw_for_grid_5 + g_raw_for_grid_6) /
  (g_raw_for_grid_7 + g_raw_for_grid_8 + g_raw_for_grid_9)
}



})
```


# Plot

Column {.sidebar data-width=150}
-----------------------------------------------------------------------

<br>
```{r}
# set the user selection sidebar

selectInput(
  'V_i',
  label = 'V_i',
  names(dt),
  selected = names(dt)[1]
  )


radioButtons(
  "show",
  "show",
  c("both", "only res", "only raw"),
  "both"
)

```


Row
-----------------------------------------------------------------------

### series name {.value-box}

```{r}

sd1 <- 
  reactive({
     round(sd(data_for_plot[, get(input$V_i)]),2)
  })

max1 <- 
  reactive({
     round(max(data_for_plot[, get(input$V_i)]),2)
  })


min1 <- 
  reactive({
     round(min(data_for_plot[, get(input$V_i)]),2)
  })

```


```{r}
renderValueBox(
  valueBox(
  value = input$V_i
  )
)

```

### sd

```{r}
renderValueBox(
  valueBox(
  value = sd1(),
  caption = "SD res",
  color = "info"
  )
)
```

### max {.value-box}

```{r}
col_max <- 
  reactive({
    if(max1() > 3*sd1()){
      "danger"
    } else if(max1() > 2*sd1()){
      "warning"
    }else{
      "success"
    }
  })



renderValueBox(
  valueBox(
  value = max1(),
  caption = "MAX res",
  color = col_max()
  )
)
```

### min {.value-box}

```{r}
col_min <- 
  reactive({
    if(min1() < -3*sd1()){
      "danger"
    } else if(min1() < -2*sd1()){
      "warning"
    }else{
      "success"
    }
  })
  
renderValueBox(
  valueBox(
  value = min1(),
  caption = "MIN res",
  color = col_min()
  )
)
```

Row
-----------------------------------------------------------------------

### 


```{r}
## create plot ----
renderPlot({
g_diff <- 
  plot_res(data_for_plot, "x", input$V_i)

g_raw <- 
  plot_raw(dt, "index", input$V_i)


if(input$show == "both"){
  g_diff / g_raw
} else if(input$show == "only raw"){
  g_raw
} else{
  g_diff
}

})
```



# data

```{r}
renderDataTable(
  datatable(dt)
)
```

# data for plot

```{r}
renderDataTable(
  datatable(data_for_plot)
)
```
