# Design

## panel and data

### **main segment**


```{r}

# set the user selecton sidebar
sliderInput("m_segment_size", label = "m_segment_size:",
            min = 0.2, max = 50, value = 25, step = 0.1)

colourInput(
  "m_segment_color", "m_segment_color", "#45688E",
  allowTransparent = TRUE, closeOnClick = TRUE)

```


### **inner segment**

```{r}

sliderInput("line_size", label = "line_size:",
            min = 0.001, max = 0.01, value = 0.004, step = 0.0005)

colourInput(
  "i_segment_color", "i_segment_color", "#07006F",
  allowTransparent = TRUE, closeOnClick = TRUE)


```

### **mean line**

```{r}

colourInput(
  "mean_color", "mean_color", "#1BFF00",
  allowTransparent = TRUE, closeOnClick = TRUE)


```

### **median line**

```{r}

colourInput(
  "median_color", "median_color", "#FF9E00",
  allowTransparent = TRUE, closeOnClick = TRUE)


```



## grid and panel

### **plot.background**

```{r}
colourInput(
  "plot_background_color", NULL, "gray98",
  allowTransparent = TRUE, closeOnClick = TRUE)
```

### **panel.background**

```{r}
colourInput(
  "panel_background_color", NULL, "gray98",
  allowTransparent = TRUE, closeOnClick = TRUE)
```

### **panel.grid**

```{r}
sliderInput("grid_size", label = "grid_size:",
            min = 0.1, max = 5, value = 0.9, step = 0.1)

colourInput(
  "grid_color", NULL, "gray70",
  allowTransparent = TRUE, closeOnClick = TRUE)
```


## labels

### **axis**

```{r}
sliderInput("axis_size", label = "axis_size:",
            min = 4, max = 20, value = 16, step = 0.25)
```

### **title**

```{r}
sliderInput("title_size", label = "title_size:",
            min = 4, max = 40, value = 28, step = 0.25)
```

### **subtitle**

```{r}
sliderInput("subtitle_size", label = "subtitle_size:",
            min = 4, max = 40, value = 16, step = 0.25)
```


### **geom text**

```{r}
sliderInput("geom_text_size", label = "geom_text_size:",
            min = 1, max = 40, value = 4.5, step = 0.25)

sliderInput("geom_text_hjust", label = "geom_text_hjust:",
            min = -2, max = 2, value = 0.205, step = 0.01)

```

